services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "9997:9997"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml

  restream-manager:
    build: .
    container_name: restream-manager
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mediamtx
